-- Table: public.ds_change_inbox

-- DROP TABLE IF EXISTS public.ds_change_inbox;

CREATE TABLE IF NOT EXISTS public.ds_change_inbox
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    object_database text COLLATE pg_catalog."default",
    object_table text COLLATE pg_catalog."default",
    object_pk_attribute text COLLATE pg_catalog."default",
    object_attribute text COLLATE pg_catalog."default",
    object_id text COLLATE pg_catalog."default",
    object_value text COLLATE pg_catalog."default",
    object_operation text COLLATE pg_catalog."default",
    object_operation_command text COLLATE pg_catalog."default",
    updated_by_server_id text COLLATE pg_catalog."default",
    update_datetime timestamp without time zone,
    updated_by_user_id text COLLATE pg_catalog."default",
    object_id_old text COLLATE pg_catalog."default",
    object_value_old text COLLATE pg_catalog."default",
    note1 text COLLATE pg_catalog."default",
    source_id integer
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.ds_change_inbox
    OWNER to postgres;